[2025-05-12T08:08:30.854+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_brewery.aggregate_breweries manual__2025-05-12T08:08:22.117177+00:00 [queued]>
[2025-05-12T08:08:30.858+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_brewery.aggregate_breweries manual__2025-05-12T08:08:22.117177+00:00 [queued]>
[2025-05-12T08:08:30.858+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-12T08:08:30.863+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): aggregate_breweries> on 2025-05-12 08:08:22.117177+00:00
[2025-05-12T08:08:30.865+0000] {standard_task_runner.py:57} INFO - Started process 2765 to run task
[2025-05-12T08:08:30.867+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_brewery', 'aggregate_breweries', 'manual__2025-05-12T08:08:22.117177+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/brewery_pipeline.py', '--cfg-path', '/tmp/tmpbt8fm2hj']
[2025-05-12T08:08:30.868+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask aggregate_breweries
[2025-05-12T08:08:30.891+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_brewery.aggregate_breweries manual__2025-05-12T08:08:22.117177+00:00 [running]> on host 0d8312ffa556
[2025-05-12T08:08:30.922+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_brewery' AIRFLOW_CTX_TASK_ID='aggregate_breweries' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T08:08:22.117177+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T08:08:22.117177+00:00'
[2025-05-12T08:08:30.922+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-12T08:08:30.923+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/aggregate_breweries.py']
[2025-05-12T08:08:30.928+0000] {subprocess.py:86} INFO - Output:
[2025-05-12T08:08:31.851+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-05-12T08:08:31.852+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-05-12T08:08:31.990+0000] {subprocess.py:93} INFO - 25/05/12 08:08:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-12T08:08:32.336+0000] {subprocess.py:93} INFO - 25/05/12 08:08:32 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-05-12T08:09:34.659+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-12T08:09:34.672+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/aggregate_breweries.py", line 56, in <module>
[2025-05-12T08:09:34.675+0000] {subprocess.py:93} INFO -     run()
[2025-05-12T08:09:34.676+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/aggregate_breweries.py", line 23, in run
[2025-05-12T08:09:34.676+0000] {subprocess.py:93} INFO -     raise TimeoutError(f"Timeout: {silver_path} n찾o encontrado ap처s {timeout} segundos.")
[2025-05-12T08:09:34.677+0000] {subprocess.py:93} INFO - TimeoutError: Timeout: /opt/***/data_lake/silver/breweries n찾o encontrado ap처s 60 segundos.
[2025-05-12T08:09:35.244+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-12T08:09:35.275+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-12T08:09:35.280+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_brewery, task_id=aggregate_breweries, execution_date=20250512T080822, start_date=20250512T080830, end_date=20250512T080935
[2025-05-12T08:09:35.293+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task aggregate_breweries (Bash command failed. The command returned a non-zero exit code 1.; 2765)
[2025-05-12T08:09:35.335+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-12T08:09:35.369+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
